version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    ports:
      - "6380:6379"
  elasticsearch:
    container_name: elasticsearch-staging
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    # network_mode: "service:elasticsearch"
    volumes:
      - /Users/oleg/data/elasticsearch-prod/data:/usr/share/elasticsearch/data:rw
#         - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=password
    ports:
      - "9200:9200"