spring:
  application:
    name: chart-service
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
#  rabbitmq:
#    username: developer
#    password: eehei4AeJein
#    host: rabbitmq-dev.service
#    port: 5672
#    tradestopic: CHART_DATA_QUEUE_DEV
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    tradestopic: CHART_DATA_QUEUE

#datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  username: root
#  password: root
#datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev2?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  username: exdevdb
#  password: KQmK82dd
#datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://birzha-aurora-preprod-cluster.cluster-cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  username: devprod
#  password: Fh24soaf8sy3
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://exprod-3-cluster.cluster-ro-cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: chartservice
  password: 89tn0sgiGPyLMarmMp23

redis:
  host: localhost
  port: 6380
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    60 MINUTE: 4;
    360 MINUTE: 5;
    1440 MINUTE: 6;
    1 HOUR: 4;
    6 HOUR: 5;
    1 DAY: 6;

elasticsearch:
  host: localhost
  port: 9200

swagger:
  enabled: true

candles:
  store-in-cache: 300

generator:
  min-period: 3 #months

scheduled:
  clean-cache: 0 */30 * ? * *
  clean-daily-data: 0 */5 * ? * *

angular:
  allowed-origins: http://localhost:4200
  sockjs-lib: https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js

server:
  port: 8060

logging:
  level:
    me.exrates.chartservice: debug