spring:
  application:
    name: chartservice
  profiles:
    active:
      - local
      - produces
#      - consumes
  datasource:
    hikari:
      connection-timeout: 1000
      idle-timeout: 180000
      max-lifetime: 600000
      connection-init-sql: SELECT 1 FROM DUAL;
      connection-test-query: SELECT 2 FROM DUAL;
      minimum-idle: 5
      maximum-pool-size: 10
      validation-timeout: 5000
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    username: developer
    password: eehei4AeJein
    host: rabbitmq-dev.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: root

ssm:
  mode: dev
  path: vLHjSkPJjB6JLVcA

elasticsearch:
  host: localhost
  port: 9200

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#      should-unregister-on-shutdown: true
#      registry-fetch-interval-seconds: 5
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    lease-renewal-interval-in-seconds: 10
#    metadata-map:
#      startup: ${random.int}

server:
  port: 8060
