spring:
  application:
    name: chart-service
  devtools:
    restart:
      enabled: true
  rabbitmq:
    username: prod
    password: Urahci3n
    host: rabbitmq-prod.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE_PROD

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://exprod-3-cluster.cluster-ro-cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: chartservice
  password: 89tn0sgiGPyLMarmMp23

redis:
  host: redis-chart-prod.service
  port: 6379
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    1 HOUR: 4;
    60 MINUTE: 4;
    6 HOUR: 5;
    360 MINUTE; 5;
    1 DAY: 6;
    1440 MINUTE; 6;

elasticsearch:
  host: elastic-chart-prod.service
  port: 9200

swagger:
  enabled: true

candles:
  store-in-cache: 300

generator:
  min-period: 3 #months

scheduled:
  clean-cache: 0 */30 * ? * *
  clean-daily-data: 0 */5 * ? * *

logging:
  level:
    me.exrates.chartservice: info