spring:
  application:
    name: chart-service
  devtools:
    restart:
      enabled: true
  rabbitmq:
    username: prod
    password: Urahci3n
    host: rabbitmq-prod.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE_PROD
    candlestopic: NEW_CANDLES_PROD

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://exprod-3-cluster.cluster-ro-cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: okostiukevych
  password: 943AJNzKGiUsWtqU

redis:
  host: redis-chart-prod.service
  port: 6379
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    1 HOUR: 4;
    6 HOUR: 5;
    1 DAY: 6;
  next-interval: >
    5 MINUTE: 15 MINUTE;
    15 MINUTE: 30 MINUTE;
    30 MINUTE: 1 HOUR;
    1 HOUR: 6 HOUR;
    6 HOUR: 1 DAY;

elasticsearch:
  host: elastic-chart-prod.service
  port: 9200

swagger:
  enabled: true

candles:
  store-in-cache: 300

scheduled:
  clean-cache: 0 */30 * ? * *
  update-cache: 0 */5 * ? * *
