spring:
  application:
    name: chart-service
  devtools:
    restart:
      enabled: true
#  change to dev
  rabbitmq:
    username: developer
    password: eehei4AeJein
    host: rabbitmq-dev.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE_DEV

#  change to dev
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev2?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: exdevdb

#  change to dev
redis:
  host: 172.10.12.21
  port: 6379
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    1 HOUR: 4;
    6 HOUR: 5;
    1 DAY: 6;
  next-interval: >
    5 MINUTE: 15 MINUTE;
    15 MINUTE: 30 MINUTE;
    30 MINUTE: 1 HOUR;
    1 HOUR: 6 HOUR;
    6 HOUR: 1 DAY;

#  change to dev
ssm:
  mode: dev
  path: /exrates/core-service/test/mysql.token

#  change to dev
elasticsearch:
  host: 172.10.12.21
  port: 9200

swagger:
  enabled: true

candles:
  store-in-cache: 300

scheduled:
  clean-cache: 0 */30 * ? * *