spring:
  application:
    name: chart-service
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  rabbitmq:
    username: developer
    password: eehei4AeJein
    host: rabbitmq-dev.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE_DEV

#datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  username: root
#password: root
#datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev2?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  username: exdevdb
#password: KQmK82dd
#datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://birzha-aurora-preprod-cluster.cluster-cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#  username: devprod
#password: Fh24soaf8sy3
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://exprod-3-cluster.cluster-ro-cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: okostiukevych
#password: 943AJNzKGiUsWtqU

redis:
  host: localhost
  port: 6379
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    1 HOUR: 4;
    6 HOUR: 5;
    1 DAY: 6;
  next-interval: >
    5 MINUTE: 15 MINUTE;
    15 MINUTE: 30 MINUTE;
    30 MINUTE: 1 HOUR;
    1 HOUR: 6 HOUR;
    6 HOUR: 1 DAY;

ssm:
  mode: dev
  path: vLHjSkPJjB6JLVcA

elasticsearch:
  host: localhost
  port: 9200

swagger:
  enabled: true

candles:
  store-in-cache: 300

scheduled:
  clean-cache: 0 */10 * ? * *

server:
  port: 8060