spring:
  application:
    name: chart-service
  devtools:
    restart:
      enabled: true
  rabbitmq:
    username: developer
    password: eehei4AeJein
    host: rabbitmq-dev.service
    port: 5672
#    listener:
#      simple:
#        concurrency: 3
#        max-concurrency: 7
    tradestopic: CHART_DATA_QUEUE_DEV

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev2?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: exdevdb
  password: KQmK82dd

redis:
  host: redis-chart-dev.service
  port: 6383
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    60 MINUTE: 4;
    360 MINUTE: 5;
    1440 MINUTE: 6;
    1 HOUR: 4;
    6 HOUR: 5;
    1 DAY: 6;

elasticsearch:
  host: elastic-chart-dev.service
  port: 9203

swagger:
  enabled: true

candles:
  store-in-cache: 300

generator:
  min-period: 3 #months

scheduled:
  clean-cache: 0 */30 * ? * *

angular:
  allowed-origins: http://localhost:4200
  sockjs-lib: https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js

logging:
  level:
    me.exrates.chartservice: info