spring:
  application:
    name: chart-service
  devtools:
    restart:
      enabled: true
#  change to preprod
  rabbitmq:
    username: developer
    password: eehei4AeJein
    host: rabbitmq-dev.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE_PREPROD

#  change to preprod
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: root

#  change to preprod
redis:
  host: localhost
  port: 6379
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    1 HOUR: 4;
    6 HOUR: 5;
    1 DAY: 6;
  next-interval: >
    5 MINUTE: 15 MINUTE;
    15 MINUTE: 30 MINUTE;
    30 MINUTE: 1 HOUR;
    1 HOUR: 6 HOUR;
    6 HOUR: 1 DAY;

#  change to preprod
ssm:
  mode: dev
  path: /exrates/core-service/preprod/mysql.token

#  change to preprod
elasticsearch:
  host: localhost
  port: 9200

candles:
  store-in-cache: 300

scheduled:
  clean-cache: 0 */30 * ? * *