spring:
  application:
    name: chart-service
  devtools:
    restart:
      enabled: true
  rabbitmq:
    username: preprod
    password: eehVBU21x
    host: rabbitmq-preprod.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE_PREPROD

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://birzha-aurora-preprod-cluster.cluster-cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: devprod
  password: Fh24soaf8sy3

redis:
  host: redis-chart-preprod.service
  port: 6381
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    60 MINUTE: 4;
    360 MINUTE: 5;
    1440 MINUTE: 6;
    1 HOUR: 4;
    6 HOUR: 5;
    1 DAY: 6;

elasticsearch:
  host: elastic-chart-preprod.service
  port: 9201

swagger:
  enabled: true

candles:
  store-in-cache: 300

generator:
  min-period: 3 #months

scheduled:
  clean-cache: 0 */30 * ? * *
  clean-daily-data: 0 */5 * ? * *

angular:
  allowed-origins: http://dev6.exapp
  sockjs-lib: https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js

logging:
  level:
    me.exrates.chartservice: info