spring:
  application:
    name: chart-service
  devtools:
    restart:
      enabled: true
  rabbitmq:
    username: developer
    password: eehei4AeJein
    host: rabbitmq-dev.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE_TEST

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://exprod-3-cluster.cluster-ro-cedlveyttji9.us-east-2.rds.amazonaws.com:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: chartservice
  password: 89tn0sgiGPyLMarmMp23

redis:
  host: 172.31.19.62
  port: 6379
  allowed-interval-db-indexes: >
    1 MINUTE: 1;
    5 MINUTE: 2;
    15 MINUTE: 3;
    30 MINUTE: 4;
    60 MINUTE: 5;
    360 MINUTE: 6;
    1440 MINUTE: 7;
    1 HOUR: 5;
    6 HOUR: 6;
    1 DAY: 7;

elasticsearch:
  host: 172.31.19.62
  port: 9200

swagger:
  enabled: true

candles:
  store-in-cache: 300

generator:
  min-period: 2 #months

scheduled:
  clean-cache: 0 */30 * ? * *

angular:
  allowed-origins: https://qa1.exrates.tech
  sockjs-lib: https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js

logging:
  level:
    me.exrates.chartservice: info