spring:
  application:
    name: chart-service
  profiles:
    active:
    - dev
    #      - produces
    - consumes
  datasource:
    hikari:
      connection-timeout: 1000
      idle-timeout: 180000
      max-lifetime: 600000
      connection-init-sql: SELECT 1 FROM DUAL;
      connection-test-query: SELECT 2 FROM DUAL;
      minimum-idle: 5
      maximum-pool-size: 10
      validation-timeout: 5000
  devtools:
    restart:
      enabled: true
#  change to dev
  rabbitmq:
    username: developer
    password: eehei4AeJein
    host: rabbitmq-dev.service
    port: 5672
    tradestopic: CHART_DATA_QUEUE_DEV

#  change to dev
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/birzha?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: root

#  change to dev
redis:
  host: localhost
  port: 6379
  allowed-interval-db-indexes: >
    5 MINUTE: 1;
    15 MINUTE: 2;
    30 MINUTE: 3;
    1 HOUR: 4;
    6 HOUR: 5;
    1 DAY: 6;
  next-interval: >
    5 MINUTE: 15 MINUTE;
    15 MINUTE: 30 MINUTE;
    30 MINUTE: 1 HOUR;
    1 HOUR: 6 HOUR;
    6 HOUR: 1 DAY;

#  change to dev
ssm:
  mode: dev
  path: /exrates/core-service/test/mysql.token

#  change to dev
elasticsearch:
  host: localhost
  port: 9200

candles:
  store-in-cache: 300

scheduled:
  update-cache: 0 */5 * ? * *
  clean-cache: 0 */5 * ? * *